### PR TITLE
Add test coverage via babel-istanbul

### PR DESCRIPTION
**Pull request by markdalgleish**
Your readme lists test coverage as a todo, and we're depending on this project in a project I'm working on, so I figured I'd send you a PR with [babel-istanbul](https://github.com/ambitioninc/babel-istanbul) hooked up :smiley:

It was actually a bit tricky to get it to play nicely with Make, so you might find the test command somewhat cryptic, but unfortunately this was out of necessity.

Thank you so much for the awesome work!

### CODE REVIEW

**Comment by danieljuhl** [comment]
Thanks! I'll have a look later today and merge, if no questions arrive.

**Comment by markdalgleish** [comment]
Have you had a chance to have a look at this? I'm keen to continue helping out in this space :smiley:

**Comment by danieljuhl** [comment]
Sorry for the delay - will handle this now. Just a few moments..

**Comment by markdalgleish** [comment]
Thanks for merging!

**Comment by danieljuhl** [comment]
Thanks for your contribution!

**Pull request merged**
